// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tankpreise.DAL.Data;

#nullable disable

namespace Tankpreise.DAL.Migrations
{
    [DbContext(typeof(TankpreiseContext))]
    partial class TankpreiseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tankpreise.DAL.Models.StationPreise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Diesel")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("diesel")
                        .HasAnnotation("Relational:JsonPropertyName", "diesel");

                    b.Property<decimal>("E10")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("e10")
                        .HasAnnotation("Relational:JsonPropertyName", "e10");

                    b.Property<decimal>("E5")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("e5")
                        .HasAnnotation("Relational:JsonPropertyName", "e5");

                    b.Property<Guid>("StationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("stations_id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.HasIndex("StationsId", "Timestamp")
                        .IsUnique();

                    b.ToTable("station_preise");
                });
#pragma warning restore 612, 618
        }
    }
}
